In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import plotly.express as plt

In [2]:
# import dataset
gdp_df = pd.read_csv('Resources/US_GDPbyState.csv')
gdp_df

,GeoName,IndustryClassification,Description,Unit,1997,1998,1999,2000,2001,2002,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,United States *,...,All industry total,Thousands of dollars,3286531000,3384012000,3592863000,3733598000,3866604000,4067108000,...,6321995000,6600532000,6870613000,7108287000,7278526000,7468126000,7736436000,8158931000,8453733000,8540393000
1,United States *,...,Private industries,Thousands of dollars,3016880000,3109566000,3309309000,3442431000,3573144000,3763375000,...,5864239000,6122329000,6381890000,6602693000,6760876000,6945418000,7201029000,7602124000,7880083000,7951504000
2,United States *,11,"Agriculture, forestry, fishing and hunting",Thousands of dollars,83125000,77455000,76136000,82571000,83047000,69350000,...,137268000,129565000,164085000,143777000,127217000,112701000,118151000,121041000,115135000,150087000
3,United States *,111-112,Farms,Thousands of dollars,72915000,67211000,65959000,71732000,72620000,59404000,...,128228000,120231000,155086000,134421000,117235000,102875000,108608000,111146000,105058000,140318000
4,United States *,113-115,"Forestry, fishing, and related activities",Thousands of dollars,10209000,10243000,10177000,10839000,10427000,9945000,...,9041000,9334000,8999000,9356000,9983000,9826000,9543000,9895000,10076000,9770000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4783,Wyoming,"42, 44-45",Trade,Thousands of dollars,453228,496155,496289,496897,513707,529079,...,763508,940537,1016462,1074153,1043055,951654,835507,811930,864871,951679
4784,Wyoming,"22, 48-49",Transportation and utilities,Thousands of dollars,576034,649227,647049,686359,(D),635572,...,1651719,1948704,2146072,2364596,2635027,2704761,2782646,3178311,3186062,(D)
4785,Wyoming,"31-33, 51",Manufacturing and information,Thousands of dollars,563997,610454,564689,605443,(D),586534,...,1605192,2010878,1399608,1143405,1768574,1147760,(D),2116409,2364638,1932934
4786,Wyoming,...,Private goods-producing industries 2/,Thousands of dollars,2509658,2046577,2168158,2662763,3398026,2909071,...,10970722,8423388,7850105,7722725,5564245,4280741,5244923,5827329,5697615,(D)
4787,Wyoming,...,Private services-providing industries 3/,Thousands of dollars,3352156,3497164,3681951,3887958,4022602,4376806,...,7857492,8715756,9076596,9667493,10099572,10041132,9773206,10322027,10276752,(D)

In [3]:
# Group by All Industry Total
gdp_df2 = gdp_df.loc[gdp_df['Description'] == "All industry total"]
gdp_df2

,GeoName,IndustryClassification,Description,Unit,1997,1998,1999,2000,2001,2002,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,United States *,...,All industry total,Thousands of dollars,3286531000,3384012000,3592863000,3733598000,3866604000,4067108000,...,6321995000,6600532000,6870613000,7108287000,7278526000,7468126000,7736436000,8158931000,8453733000,8540393000
96,Alabama,...,All industry total,Thousands of dollars,37247871,39368055,41513658,42583368,43348584,45807070,...,73907390,77608112,80917965,79561954,80669851,82073865,85542583,88794676,90113804,90732519
188,Alaska,...,All industry total,Thousands of dollars,11061328,9388659,9690070,10455709,11337091,11963659,...,25196229,24819072,22642550,23858117,20819352,20355484,22290191,22145776,21075569,18458293
280,Arizona,...,All industry total,Thousands of dollars,53776045,57020794,62895447,62781317,64896111,70104348,...,102540936,107076842,108778205,111436819,115827947,121628893,127579755,133408037,141253730,147062277
372,Arkansas,...,All industry total,Thousands of dollars,23315960,23736909,25718358,25974140,26235659,27860168,...,41614398,41542915,44449432,45138072,44687986,44409534,44820156,47015337,48326336,49887987
464,California,...,All industry total,Thousands of dollars,431069388,453030898,487837764,509912047,514711563,537381330,...,831169134,869106609,922208690,959787034,1000092213,1038406767,1112086603,1181112341,1235258375,1245131643
556,Colorado,...,All industry total,Thousands of dollars,52989433,57765105,62638825,66474953,68887729,72171780,...,107126647,109663061,118145395,123575170,125444130,128087520,134076309,142335424,148662737,147403256
648,Connecticut,...,All industry total,Thousands of dollars,50568520,51906772,53755314,59834228,62264569,64527991,...,93431387,96584621,94992103,95466076,103889605,106714047,112460917,117028990,120457808,116383792
740,Delaware,...,All industry total,Thousands of dollars,16293486,18697289,20725145,22478806,24465286,23211328,...,31992549,32022426,30633048,35588454,38102060,35114205,32884557,35073261,38066566,38805576
832,District of Columbia,...,All industry total,Thousands of dollars,14800959,15341732,16243372,16094689,17549116,19129987,...,31043292,31856203,32742759,33910701,35440241,37123871,37255087,38546918,40041005,41679868
924,Florida,...,All industry total,Thousands of dollars,142316948,147761064,159175918,168100246,179503513,196626046,...,284517947,290315223,304170076,320495370,345661500,363341307,378542904,395362274,418578557,441215245
1016,Georgia,...,All industry total,Thousands of dollars,94784598,103983227,115229711,117796713,123715682,130323368,...,173984476,180493987,188219697,198965352,215187361,228708383,241383375,251826630,270875222,269536010
1108,Hawaii,...,All industry total,Thousands of dollars,13552691,12914176,13574252,14200772,14660447,14976392,...,25176206,26142347,27316387,27453755,29521263,30437354,31682075,32467152,32463308,31098046
1200,Idaho,...,All industry total,Thousands of dollars,11392168,11868189,13679421,15505965,14407468,14710293,...,24372959,24855218,26450035,27677791,27287519,28053771,27722954,30449865,32975934,34572573
1292,Illinois,...,All industry total,Thousands of dollars,151296561,154671781,162498548,170702267,175118486,181132977,...,268839866,285004508,289548643,303148201,309853325,310835238,312617136,330694098,339292886,339030551
1384,Indiana,...,All industry total,Thousands of dollars,61982144,68704906,70630195,75097775,75143840,79411008,...,127599109,128431395,136323553,144315634,141898179,145313995,149213510,159085173,160670234,164193967
1476,Iowa,...,All industry total,Thousands of dollars,34799429,33538694,34728248,37638675,37487314,38804401,...,66060760,71732325,73119568,79211114,83472223,80524778,80070685,83126643,85168924,89949005
1568,Kansas,...,All industry total,Thousands of dollars,27382937,27898288,29103199,30136943,30798406,31815224,...,55181605,57954923,57845166,60201305,62249390,66847263,69065951,72565732,74212017,76735624
1660,Kentucky,...,All industry total,Thousands of dollars,41490635,42902228,44408081,39217929,39995834,42427197,...,65226749,67810648,72792905,72395718,72691981,73388947,75020817,76837415,79984427,81925526
1752,Louisiana,...,All industry total,Thousands of dollars,47340324,46982396,50997264,54827194,55648781,54523463,...,109636675,111003063,102489834,106610216,99413853,91992415,102531949,111896530,108100142,101362671
1844,Maine,...,All industry total,Thousands of dollars,9998624,10208631,11289437,12297031,12638012,13406013,...,18518144,18762059,18692865,19230453,19386205,20366830,21130874,22234959,23178748,24965657
1936,Maryland,...,All industry total,Thousands of dollars,57249287,60621374,63910668,66140409,72675437,77810311,...,127703265,128873109,133480890,137305143,145211912,156335887,161053365,162794268,164597012,162820677
2028,Massachusetts,...,All industry total,Thousands of dollars,90725167,91037944,93358949,97109045,101675643,108319852,...,164548868,171456951,174178643,176005220,186845408,193427479,194909607,208366189,219834820,224542970
2120,Michigan,...,All industry total,Thousands of dollars,101943999,103223844,115645001,115576766,114166042,126743755,...,148137691,158071357,166082249,170591427,180768044,185778425,184912884,190079774,192427754,202035729
2212,Minnesota,...,All industry total,Thousands of dollars,54159465,55832211,58892965,64313753,64244748,68494099,...,108721935,114686600,119552997,125346100,126974629,128607071,129318554,138362540,140751061,145238827
2304,Mississippi,...,All industry total,Thousands of dollars,21296263,20995269,22309578,22546057,23792090,23922545,...,37173603,38943343,39559655,39392186,39770829,39712499,40854836,41251011,41723814,43136956
2396,Missouri,...,All industry total,Thousands of dollars,62103799,62605015,64759103,67032566,68042829,71023185,...,102898802,106472197,110490883,112504139,114179335,114738968,114990262,116699408,122414492,128088097
2488,Montana,...,All industry total,Thousands of dollars,7578587,8195805,8249529,8453149,8827632,9009373,...,18133916,18323270,18963160,19343393,19837427,18244780,19848722,20878777,20579328,21239923
2580,Nebraska,...,All industry total,Thousands of dollars,19352109,19920909,20462692,21294227,22594810,22189767,...,46622938,46691939,49888802,51431141,53288905,53446292,54602919,56378838,58660843,63387282
2672,Nevada,...,All industry total,Thousands of dollars,22608526,23858893,26310389,28205042,29124565,31824495,...,52778287,52575554,52710673,51800223,56107618,57315065,61870205,64548322,70672743,68683347
2764,New Hampshire,...,All industry total,Thousands of dollars,15319685,15737825,15500604,16218488,16594149,18187518,...,24797858,26218397,26808891,26930629,28458846,29427237,28919646,29925080,31331286,32691427
2856,New Jersey,...,All industry total,Thousands of dollars,113056436,110113325,116530569,122851600,130313941,135870292,...,180443507,192371484,198724993,196768998,205616688,212139527,211187432,221178948,229121612,232219841
2948,New Mexico,...,All industry total,Thousands of dollars,25921222,22877383,24291871,24481286,23522192,24034122,...,38782975,38028663,38284739,39747026,36828351,36043946,36951552,38417611,40268292,40040022
3040,New York,...,All industry total,Thousands of dollars,285946225,282284655,305524470,309367024,333484465,350262890,...,488737584,544781091,556535506,579531277,600087873,648249312,656017578,698931750,740451581,752989816
3132,North Carolina,...,All industry total,Thousands of dollars,93019850,95791934,104006018,105673196,111365119,117168587,...,180758214,183676468,194848743,201028040,214148277,221613483,231848399,234913002,244422229,246965092
3224,North Dakota,...,All industry total,Thousands of dollars,5905652,6670856,6829669,7416129,7514242,7847347,...,18498784,24666522,25184551,27082443,23542916,21794553,23981171,26442525,25249243,24265870
3316,Ohio,...,All industry total,Thousands of dollars,125809478,131812178,135445776,140147002,140143054,149294152,...,210736751,215642272,224319088,238573317,241552672,246050997,250161684,262387946,274638970,281213884
3408,Oklahoma,...,All industry total,Thousands of dollars,30165634,29450908,30636002,33284697,36288673,37554876,...,74004962,77120520,81499207,91512324,79681426,76066497,82001611,87587416,85007480,76831726
3500,Oregon,...,All industry total,Thousands of dollars,40064349,40963900,40000502,43349143,41632269,44745560,...,69624171,68306503,69425216,72301466,77339835,81718264,85402691,91404427,93946367,96766771
3592,Pennsylvania,...,All industry total,Thousands of dollars,130253499,133482318,137857913,141053171,148416954,155951987,...,243508304,255480253,264727225,277962868,280686985,287214957,289003670,296443067,304077861,305433346
3684,Rhode Island,...,All industry total,Thousands of dollars,10175217,10932659,11355707,12006684,12445787,13296754,...,18692273,19231710,19638155,19678454,20134275,20234481,19526479,19590797,20420584,21720995
3776,South Carolina,...,All industry total,Thousands of dollars,35309495,36681050,39301857,40242728,42303219,45711667,...,64607260,66667631,69687992,72838086,78308632,82965421,84467504,87292615,90888106,97218705
3868,South Dakota,...,All industry total,Thousands of dollars,8080749,8684188,8995035,9851029,10123067,12112743,...,21041933,22232138,23096763,23230350,23458620,23840544,23661227,24755210,25307340,27208415
3960,Tennessee,...,All industry total,Thousands of dollars,56801075,63996478,66809667,66815565,68719421,74042089,...,109184981,115871600,121955474,126063848,135548922,140041740,144997967,146385827,153014100,154136800
4052,Texas,...,All industry total,Thousands of dollars,244940931,245730444,253513188,274635932,290137214,299342483,...,602528379,631841562,690780835,697595832,651005312,643212402,695116571,760496913,761475943,724665153
4144,Utah,...,All industry total,Thousands of dollars,21611078,23178629,24521916,25717049,26481063,28312768,...,53731776,53771326,55922231,58860648,60971601,64347698,68306518,75454010,81013569,83959971
4236,Vermont,...,All industry total,Thousands of dollars,5209710,5198976,5605599,5948586,6220161,6704058,...,10167482,10418139,9766057,10141059,10157237,10454958,10376824,10421009,10853175,11584063
4328,Virginia,...,All industry total,Thousands of dollars,76237621,81875337,89269685,93412407,101719007,106519408,...,161081063,164164915,170065863,170317825,176256905,181008174,182237787,190659806,198374474,200788106
4420,Washington,...,All industry total,Thousands of dollars,72446364,76716314,85342390,84431546,83915753,89565770,...,156428257,164742044,172425558,179315440,192208394,196197171,207658653,225366279,235792290,248091869
4512,West Virginia,...,All industry total,Thousands of dollars,13885061,14251705,14934606,14530030,14893501,15912071,...,27882629,27536254,28397299,29063742,27582854,28084699,29981286,30881617,30844355,31157223
4604,Wisconsin,...,All industry total,Thousands of dollars,50462289,53446908,56541841,58484581,61242423,63661637,...,97389504,102582684,104565186,110768548,116315970,118370109,115808647,120256505,125860109,128759365
4696,Wyoming,...,All industry total,Thousands of dollars,6273127,5977972,6312016,7028346,7918039,7809796,...,19614591,18004944,17809599,18271502,16516120,15164898,15976363,17122283,16978835,15469645

In [4]:
# Drop unneccessary columns
gdp_df2 = gdp_df2.drop(['IndustryClassification', 'Description', 'Unit'], axis = 1)
gdp_df2

,GeoName,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,United States *,3286531000,3384012000,3592863000,3733598000,3866604000,4067108000,4337585000,4666176000,5079950000,...,6321995000,6600532000,6870613000,7108287000,7278526000,7468126000,7736436000,8158931000,8453733000,8540393000
96,Alabama,37247871,39368055,41513658,42583368,43348584,45807070,49100590,57547042,63136982,...,73907390,77608112,80917965,79561954,80669851,82073865,85542583,88794676,90113804,90732519
188,Alaska,11061328,9388659,9690070,10455709,11337091,11963659,13311189,15436621,19019065,...,25196229,24819072,22642550,23858117,20819352,20355484,22290191,22145776,21075569,18458293
280,Arizona,53776045,57020794,62895447,62781317,64896111,70104348,77869673,81311943,90811873,...,102540936,107076842,108778205,111436819,115827947,121628893,127579755,133408037,141253730,147062277
372,Arkansas,23315960,23736909,25718358,25974140,26235659,27860168,30737525,33626013,36232114,...,41614398,41542915,44449432,45138072,44687986,44409534,44820156,47015337,48326336,49887987
464,California,431069388,453030898,487837764,509912047,514711563,537381330,581749924,609807535,669808719,...,831169134,869106609,922208690,959787034,1000092213,1038406767,1112086603,1181112341,1235258375,1245131643
556,Colorado,52989433,57765105,62638825,66474953,68887729,72171780,76283527,78021070,87175950,...,107126647,109663061,118145395,123575170,125444130,128087520,134076309,142335424,148662737,147403256
648,Connecticut,50568520,51906772,53755314,59834228,62264569,64527991,66380943,76332073,81040630,...,93431387,96584621,94992103,95466076,103889605,106714047,112460917,117028990,120457808,116383792
740,Delaware,16293486,18697289,20725145,22478806,24465286,23211328,24421185,26159662,25434871,...,31992549,32022426,30633048,35588454,38102060,35114205,32884557,35073261,38066566,38805576
832,District of Columbia,14800959,15341732,16243372,16094689,17549116,19129987,19891320,21945440,23285267,...,31043292,31856203,32742759,33910701,35440241,37123871,37255087,38546918,40041005,41679868
924,Florida,142316948,147761064,159175918,168100246,179503513,196626046,211888269,235074193,259016363,...,284517947,290315223,304170076,320495370,345661500,363341307,378542904,395362274,418578557,441215245
1016,Georgia,94784598,103983227,115229711,117796713,123715682,130323368,138635361,149166265,161578076,...,173984476,180493987,188219697,198965352,215187361,228708383,241383375,251826630,270875222,269536010
1108,Hawaii,13552691,12914176,13574252,14200772,14660447,14976392,16496177,18154600,20700992,...,25176206,26142347,27316387,27453755,29521263,30437354,31682075,32467152,32463308,31098046
1200,Idaho,11392168,11868189,13679421,15505965,14407468,14710293,15528521,17488981,19948858,...,24372959,24855218,26450035,27677791,27287519,28053771,27722954,30449865,32975934,34572573
1292,Illinois,151296561,154671781,162498548,170702267,175118486,181132977,192990901,206658933,216613099,...,268839866,285004508,289548643,303148201,309853325,310835238,312617136,330694098,339292886,339030551
1384,Indiana,61982144,68704906,70630195,75097775,75143840,79411008,87295448,94968754,96117493,...,127599109,128431395,136323553,144315634,141898179,145313995,149213510,159085173,160670234,164193967
1476,Iowa,34799429,33538694,34728248,37638675,37487314,38804401,43458112,51889675,55481162,...,66060760,71732325,73119568,79211114,83472223,80524778,80070685,83126643,85168924,89949005
1568,Kansas,27382937,27898288,29103199,30136943,30798406,31815224,34201838,34165552,38479471,...,55181605,57954923,57845166,60201305,62249390,66847263,69065951,72565732,74212017,76735624
1660,Kentucky,41490635,42902228,44408081,39217929,39995834,42427197,45395875,48511524,53525805,...,65226749,67810648,72792905,72395718,72691981,73388947,75020817,76837415,79984427,81925526
1752,Louisiana,47340324,46982396,50997264,54827194,55648781,54523463,66745302,78333391,102972988,...,109636675,111003063,102489834,106610216,99413853,91992415,102531949,111896530,108100142,101362671
1844,Maine,9998624,10208631,11289437,12297031,12638012,13406013,14040252,15434894,16643081,...,18518144,18762059,18692865,19230453,19386205,20366830,21130874,22234959,23178748,24965657
1936,Maryland,57249287,60621374,63910668,66140409,72675437,77810311,82379142,89164719,95717611,...,127703265,128873109,133480890,137305143,145211912,156335887,161053365,162794268,164597012,162820677
2028,Massachusetts,90725167,91037944,93358949,97109045,101675643,108319852,113957689,117149202,125286617,...,164548868,171456951,174178643,176005220,186845408,193427479,194909607,208366189,219834820,224542970
2120,Michigan,101943999,103223844,115645001,115576766,114166042,126743755,130910973,135105302,142900057,...,148137691,158071357,166082249,170591427,180768044,185778425,184912884,190079774,192427754,202035729
2212,Minnesota,54159465,55832211,58892965,64313753,64244748,68494099,75853506,83354383,92982600,...,108721935,114686600,119552997,125346100,126974629,128607071,129318554,138362540,140751061,145238827
2304,Mississippi,21296263,20995269,22309578,22546057,23792090,23922545,27026194,28212293,30666324,...,37173603,38943343,39559655,39392186,39770829,39712499,40854836,41251011,41723814,43136956
2396,Missouri,62103799,62605015,64759103,67032566,68042829,71023185,75561166,81223673,85508511,...,102898802,106472197,110490883,112504139,114179335,114738968,114990262,116699408,122414492,128088097
2488,Montana,7578587,8195805,8249529,8453149,8827632,9009373,10033834,11383893,12959014,...,18133916,18323270,18963160,19343393,19837427,18244780,19848722,20878777,20579328,21239923
2580,Nebraska,19352109,19920909,20462692,21294227,22594810,22189767,25378406,27307524,30008760,...,46622938,46691939,49888802,51431141,53288905,53446292,54602919,56378838,58660843,63387282
2672,Nevada,22608526,23858893,26310389,28205042,29124565,31824495,33917673,39143920,44841170,...,52778287,52575554,52710673,51800223,56107618,57315065,61870205,64548322,70672743,68683347
2764,New Hampshire,15319685,15737825,15500604,16218488,16594149,18187518,19285221,20491230,20972432,...,24797858,26218397,26808891,26930629,28458846,29427237,28919646,29925080,31331286,32691427
2856,New Jersey,113056436,110113325,116530569,122851600,130313941,135870292,141852875,142931676,151590167,...,180443507,192371484,198724993,196768998,205616688,212139527,211187432,221178948,229121612,232219841
2948,New Mexico,25921222,22877383,24291871,24481286,23522192,24034122,27154611,31897158,33656552,...,38782975,38028663,38284739,39747026,36828351,36043946,36951552,38417611,40268292,40040022
3040,New York,285946225,282284655,305524470,309367024,333484465,350262890,354833478,372164019,387437436,...,488737584,544781091,556535506,579531277,600087873,648249312,656017578,698931750,740451581,752989816
3132,North Carolina,93019850,95791934,104006018,105673196,111365119,117168587,123138727,131137940,145225662,...,180758214,183676468,194848743,201028040,214148277,221613483,231848399,234913002,244422229,246965092
3224,North Dakota,5905652,6670856,6829669,7416129,7514242,7847347,9180388,9272135,10242896,...,18498784,24666522,25184551,27082443,23542916,21794553,23981171,26442525,25249243,24265870
3316,Ohio,125809478,131812178,135445776,140147002,140143054,149294152,153840345,164363589,177846639,...,210736751,215642272,224319088,238573317,241552672,246050997,250161684,262387946,274638970,281213884
3408,Oklahoma,30165634,29450908,30636002,33284697,36288673,37554876,41875809,46201592,53552261,...,74004962,77120520,81499207,91512324,79681426,76066497,82001611,87587416,85007480,76831726
3500,Oregon,40064349,40963900,40000502,43349143,41632269,44745560,48498083,52942517,55984976,...,69624171,68306503,69425216,72301466,77339835,81718264,85402691,91404427,93946367,96766771
3592,Pennsylvania,130253499,133482318,137857913,141053171,148416954,155951987,165373968,176091889,185562853,...,243508304,255480253,264727225,277962868,280686985,287214957,289003670,296443067,304077861,305433346
3684,Rhode Island,10175217,10932659,11355707,12006684,12445787,13296754,13610732,15039142,16023460,...,18692273,19231710,19638155,19678454,20134275,20234481,19526479,19590797,20420584,21720995
3776,South Carolina,35309495,36681050,39301857,40242728,42303219,45711667,48554964,49204714,53000895,...,64607260,66667631,69687992,72838086,78308632,82965421,84467504,87292615,90888106,97218705
3868,South Dakota,8080749,8684188,8995035,9851029,10123067,12112743,12535612,13614743,14875169,...,21041933,22232138,23096763,23230350,23458620,23840544,23661227,24755210,25307340,27208415
3960,Tennessee,56801075,63996478,66809667,66815565,68719421,74042089,77725283,83882262,90191698,...,109184981,115871600,121955474,126063848,135548922,140041740,144997967,146385827,153014100,154136800
4052,Texas,244940931,245730444,253513188,274635932,290137214,299342483,328901912,382306721,427799913,...,602528379,631841562,690780835,697595832,651005312,643212402,695116571,760496913,761475943,724665153
4144,Utah,21611078,23178629,24521916,25717049,26481063,28312768,29891637,33214156,38546005,...,53731776,53771326,55922231,58860648,60971601,64347698,68306518,75454010,81013569,83959971
4236,Vermont,5209710,5198976,5605599,5948586,6220161,6704058,7029067,7812445,7765020,...,10167482,10418139,9766057,10141059,10157237,10454958,10376824,10421009,10853175,11584063
4328,Virginia,76237621,81875337,89269685,93412407,101719007,106519408,111319249,116555630,127336572,...,161081063,164164915,170065863,170317825,176256905,181008174,182237787,190659806,198374474,200788106
4420,Washington,72446364,76716314,85342390,84431546,83915753,89565770,93420918,97280742,111906626,...,156428257,164742044,172425558,179315440,192208394,196197171,207658653,225366279,235792290,248091869
4512,West Virginia,13885061,14251705,14934606,14530030,14893501,15912071,16457345,17634797,19833933,...,27882629,27536254,28397299,29063742,27582854,28084699,29981286,30881617,30844355,31157223
4604,Wisconsin,50462289,53446908,56541841,58484581,61242423,63661637,67530696,72218968,79326110,...,97389504,102582684,104565186,110768548,116315970,118370109,115808647,120256505,125860109,128759365
4696,Wyoming,6273127,5977972,6312016,7028346,7918039,7809796,9065568,10345867,13222201,...,19614591,18004944,17809599,18271502,16516120,15164898,15976363,17122283,16978835,15469645

In [12]:
# Stack Years into a column
gdp_df3 = gdp_df2.set_index(['GeoName']).stack()\
    .reset_index(name = "GDP").rename(columns={'level_1':'Year', 'GeoName':'State'})
gdp_df3

                State  Year         GDP
0     United States *  1997  3286531000
1     United States *  1998  3384012000
2     United States *  1999  3592863000
3     United States *  2000  3733598000
4     United States *  2001  3866604000
...               ...   ...         ...
1243          Wyoming  2016    15164898
1244          Wyoming  2017    15976363
1245          Wyoming  2018    17122283
1246          Wyoming  2019    16978835
1247          Wyoming  2020    15469645

[1248 rows x 3 columns]

In [13]:
# Replace "United States *" with "United States"
gdp_df3['State'] = gdp_df3['State'].str.replace(r'United States \*', r'United States')

gdp_df3

C:\ProgramData\Anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

              State  Year         GDP
0     United States  1997  3286531000
1     United States  1998  3384012000
2     United States  1999  3592863000
3     United States  2000  3733598000
4     United States  2001  3866604000
...             ...   ...         ...
1243        Wyoming  2016    15164898
1244        Wyoming  2017    15976363
1245        Wyoming  2018    17122283
1246        Wyoming  2019    16978835
1247        Wyoming  2020    15469645

[1248 rows x 3 columns]

In [16]:
# Multiply GDP by 1000 (in excel) to get actual GDP numbers
gdp_df3.to_csv('Resources/US_GDPbyState1.csv')

In [49]:
# Re-import data and import state abbreviations
gdp_df4 = pd.read_csv('Resources/US_GDPbyState1.csv')
state_abbrev = pd.read_csv('Resources/StateAbbrev.csv')
print(gdp_df4)
print(state_abbrev)

              State  Year           GDP
0     United States  1997  3.286530e+12
1     United States  1998  3.384010e+12
2     United States  1999  3.592860e+12
3     United States  2000  3.733600e+12
4     United States  2001  3.866600e+12
...             ...   ...           ...
1243        Wyoming  2016  1.516490e+10
1244        Wyoming  2017  1.597636e+10
1245        Wyoming  2018  1.712228e+10
1246        Wyoming  2019  1.697884e+10
1247        Wyoming  2020  1.546964e+10

[1248 rows x 3 columns]
                   State Abbrev
0          United States    USA
1                ALABAMA     AL
2                 ALASKA     AK
3                ARIZONA     AZ
4               ARKANSAS     AR
5             CALIFORNIA     CA
6               COLORADO     CO
7            CONNECTICUT     CT
8               DELAWARE     DE
9   DISTRICT OF COLUMBIA     DC
10               FLORIDA     FL
11               GEORGIA     GA
12                  GUAM     GU
13                HAWAII     HI
14                 IDAHO     ID
15              ILLINOIS     IL
16               INDIANA     IN
17                  IOWA     IA
18                KANSAS     KS
19              KENTUCKY     KY
20             LOUISIANA     LA
21                 MAINE     ME
22              MARYLAND     MD
23         MASSACHUSETTS     MA
24              MICHIGAN     MI
25             MINNESOTA     MN
26           MISSISSIPPI     MS
27              MISSOURI     MO
28               MONTANA     MT
29              NEBRASKA     NE
30                NEVADA     NV
31         NEW HAMPSHIRE     NH
32            NEW JERSEY     NJ
33            NEW MEXICO     NM
34              NEW YORK     NY
35        NORTH CAROLINA     NC
36          NORTH DAKOTA     ND
37   NORTHERN MARIANA IS     MP
38                  OHIO     OH
39              OKLAHOMA     OK
40                OREGON     OR
41          PENNSYLVANIA     PA
42          RHODE ISLAND     RI
43        SOUTH CAROLINA     SC
44          SOUTH DAKOTA     SD
45             TENNESSEE     TN
46                 TEXAS     TX
47                  UTAH     UT
48               VERMONT     VT
49              VIRGINIA     VA
50        VIRGIN ISLANDS     VI
51            WASHINGTON     WA
52         WEST VIRGINIA     WV
53             WISCONSIN     WI
54               WYOMING     WY

In [56]:
#Add abbrev column to gdp_df
gdp_df4['state_lower'] = gdp_df4['State'].str.lower()
state_abbrev['state_lower'] = state_abbrev['State'].str.lower()
gdp_df_cleaned = gdp_df4.merge(state_abbrev, on="state_lower", how="inner")\
    .drop(['State_y', 'state_lower'], axis = 1)\
    .rename(columns ={'State_x':'State'})
gdp_df_cleaned = gdp_df_cleaned[['State', 'Abbrev', 'Year', 'GDP']]
gdp_df_cleaned

              State Abbrev  Year           GDP
0     United States    USA  1997  3.286530e+12
1     United States    USA  1998  3.384010e+12
2     United States    USA  1999  3.592860e+12
3     United States    USA  2000  3.733600e+12
4     United States    USA  2001  3.866600e+12
...             ...    ...   ...           ...
1243        Wyoming     WY  2016  1.516490e+10
1244        Wyoming     WY  2017  1.597636e+10
1245        Wyoming     WY  2018  1.712228e+10
1246        Wyoming     WY  2019  1.697884e+10
1247        Wyoming     WY  2020  1.546964e+10

[1248 rows x 4 columns]

In [57]:
# Export cleaned data to csv
gdp_df_cleaned.to_csv('Resources/US_GDPbyState_Cleaned.csv')