In [15]:
# Import pandas
import pandas as pd

In [16]:
# Import data
pop_df = pd.read_csv('Resources/US_PopbyState.csv')
pop_df

        State  Yearly July 1st Estimates  Population
0     Alabama                     1990.0     4050055
1     Alabama                     1991.0     4099156
2     Alabama                     1992.0     4154014
3     Alabama                     1993.0     4214202
4     Alabama                     1994.0     4260229
...       ...                        ...         ...
1628  Wyoming                     2018.0      579054
1629  Wyoming                     2019.0      580116
1630  Wyoming                     2020.0      582328
1631  Wyoming                        NaN    16324618
1632      NaN                        NaN  9111858979

[1633 rows x 3 columns]

In [17]:
# Drop 'Totals' rows
pop_df = pop_df.dropna()

In [18]:
# Rename Year column
pop_df['Year'] = pop_df['Yearly July 1st Estimates']
pop_df.drop('Yearly July 1st Estimates', axis = 1, inplace = True)
pop_df = pop_df[['State', 'Year', 'Population']]
pop_df

C:\ProgramData\Anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\envs\mlenv\lib\site-packages\pandas\core\frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

        State    Year  Population
0     Alabama  1990.0     4050055
1     Alabama  1991.0     4099156
2     Alabama  1992.0     4154014
3     Alabama  1993.0     4214202
4     Alabama  1994.0     4260229
...       ...     ...         ...
1626  Wyoming  2016.0      585243
1627  Wyoming  2017.0      579994
1628  Wyoming  2018.0      579054
1629  Wyoming  2019.0      580116
1630  Wyoming  2020.0      582328

[1581 rows x 3 columns]

In [21]:
# Removing decimal from year column
pop_df.style.set_precision(0)

C:\ProgramData\Anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  """Entry point for launching an IPython kernel.

In [22]:
# Export cleaned csv
pop_df.to_csv('Resources/US_PopbyState_Cleaned.csv')